servers:
- name: red
  path: /home/jeinerox/minecraft/server
  backup_count: 2
  backup_path: /home/jeinerox/minecraft/backups
  world_name: PUZZLEFUCKERS
  memory: -Xmx3G
  auto_restart: false
  start_on_launch: true
- name: flat
  path: /home/jeinerox/minecraft/server_superflat
  memory: -Xmx3G
  auto_restart: false
  start_on_launch: false
